### ISSUE TITLE
Global default config

### ISSUE THREAD

**Issue by B-3PO** [Routefusion/routefusion-node#2]
https://github.com/Routefusion/routefusion-node/blob/e9ebeb382a8f67f3fa4f5a19ab22e7eace70c65e/index.js#L8

Most users will want to config in a single location and import in many locations without the need to multiple configurations. This should be possible without requiring multiple authentications.

one approach is to keep a global instance
This will also allow you to create multiple configs with separate instances

```javascript
// default export will be the global instance
module.exports = new Instance();
// init will generate a new instance
module.exports.init = (config) => new Instance(config);


class Instance() {
  constructor(config = {}) {
    this.config = config;
  }
  
  // an explicit method to update config
  setConfig(config) {
    this.config = Object.assign(this.config, config);
  }
}
```

**Comment by txssseal** [comment]
This is nice.  Good recommendation. @Richard-Scap what do you think?

**Comment by Richard-Scap** [comment]
This is great. +1 👍
